fieldLayouts:
  0fc34b3a-fe28-4ba0-a096-fbf4eff6eb39:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: home
hasUrls: true
name: Home
settings:
  path: '@webroot/uploads/home'
sortOrder: 1
type: craft\volumes\Local
url: '@web/uploads/home'
