enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  4e464859-cb17-4e6f-a71a-bdd0dc95fbac:
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
